# Customer Management API ConfigMap
# Assignment UUID: e271b052-9200-4502-b491-62f1649c07
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-management-api-config
  labels:
    app: customer-management-api
    assignment-uuid: e271b052-9200-4502-b491-62f1649c07
data:
  mongodb-uri: "mongodb://mongodb-service:27017/purchases"
  kafka-brokers: "kafka-service:9092"
  kafka-topic: "purchases"

