# Customer Facing Web Server Service
# Assignment UUID: e271b052-9200-4502-b491-62f1649c07
apiVersion: v1
kind: Service
metadata:
  name: customer-facing-server-service
  labels:
    app: customer-facing-server
    assignment-uuid: e271b052-9200-4502-b491-62f1649c07
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: customer-facing-server
    assignment-uuid: e271b052-9200-4502-b491-62f1649c07

