# Kustomization file for easy deployment
# Assignment UUID: e271b052-9200-4502-b491-62f1649c07
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - customer-management-api/deployment.yaml
  - customer-management-api/service.yaml
  - customer-management-api/configmap.yaml
  - customer-management-api/hpa.yaml
  - customer-facing-server/deployment.yaml
  - customer-facing-server/service.yaml
  - customer-facing-server/configmap.yaml
  - customer-facing-server/hpa.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml

commonLabels:
  assignment-uuid: e271b052-9200-4502-b491-62f1649c07

